Adding translation to portuguese
s0ftik3/burnbg-bot pull request #9
Opened 2021-09-17 15:51 UTC by douglasgusson

- I created the translation file (`src/locales/pt-br.yaml`) according to the `src/locales/en.yaml` structure.
- And I added my name to the readme translators list.

2021-09-17 16:06 UTC, s0ftik3 requested changes
Thanks for your contribution! Please, do not change any other files except locale ones. I will add you to README myself.

2021-09-17 16:54 UTC, douglasgusson commented
Okay, sorry. I removed the commit with the README change.

2021-09-17 17:00 UTC, s0ftik3 commented
Thanks. I will merge it with the coming 1.5.0 update, so don't close this PR.

2021-09-18 19:00 UTC, s0ftik3 approved these changes

2021-09-18 19:02 UTC, merged